---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ollama
  name: ollama
spec:
  type: NodePort
  ports:
    - name: http
      port: 11434
      protocol: TCP
      targetPort: 11434
  selector:
    app: ollama

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: ollama
  name: ollama
spec:
  replicas: 1
#  strategy:
#    type: RollingUpdate # Recreate, RollingUpdate
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
      name: ollama
    spec:
      ###  TAINT MODE ###
      tolerations:
        - key: "gpu-only"
          operator: "Equal"
          value: "yes"
          effect: "NoSchedule"
      nodeSelector:
        gpu-only: "yes"
      ###  TAINT MODE ###
      serviceAccountName: ollama
      containers:
        - name: ollama
          lifecycle:
           postStart:
             exec:
               command: ["/bin/sh", "-c", "ollama pull llama3 && ollama pull nomic-embed-text && touch /opt/done"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ollama/ollama:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11434
              protocol: TCP
          # resources:
          #    limits:
          #      cpu: 5000m
          #      memory: 6Gi
          #    requests:
          #      cpu: 2000m
          #      memory: 3000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
         livenessProbe:
           failureThreshold: 30
           tcpSocket:
             port: 11434
           initialDelaySeconds: 30
           timeoutSeconds: 10
         readinessProbe:
           tcpSocket:
             port: 11434
           initialDelaySeconds: 20
           timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
